# Generated by Django 2.2.18 on 2021-05-14 07:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0014_json_to_jsonb'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historyentry',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='historyentry__createdat__brin'),
        ),
    ]
